package org.datakurator.ffdq.annotations;

public enum Dimension {
    VALUE, VOCAB_MATCH, COMPLETENESS, ACCURACY, PRECISION, UNIQUENESS, RESOLUTION, CONFORMANCE, RELIABILITY, CONSISTENCY, LIKELYHOOD
}